/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sandbox;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

      int size = 100;
      Map<Integer, Map<Integer, Set<Integer>>> result = new HashMap<>();

      for (int a = 1; a <= size; a++) {
        for (int b = a; b <= size; b++) {

          Double x = Math.sqrt (
            (a*a + b*b) / (a*b + 1)
          );

          if (x % 1 == 0) {

            if (x == 1 ) continue;

            Map<Integer, Set<Integer>> main = result.getOrDefault(a, new HashMap<>());
            
            Set<Integer> data = main.getOrDefault(x.intValue(), new HashSet<>());
            data.add(b);

            main.put(x.intValue(), data);
            result.put(a, main);
            
          }
          
        }
      }

      result.forEach(
        (k,v) -> {
          System.out.println(k + " : " + v);
        }
      );
      // System.out.println(result);
      // System.out.println(String.format("a = %d, b = $d, x = %d", , v[0], v[1]))

    }
}
