/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sandbox;

import static org.junit.Assert.fail;

import java.net.MalformedURLException;
import java.net.URI;

import org.junit.Test;

public class AppTest {

  @Test
  public void testAppHasAGreeting() throws MalformedURLException {


      System.out.println(
      URI.create("/aa.com/aaaa").getFragment());

      fail("dummy");

    }
}
